import type { Metadata } from "next";
import { Platypi } from "next/font/google";
import "./globals.css";
import Header from "@/_ui/Header";
import Sidebar from "@/_ui/Sidebar";

const platypi = Platypi({
  subsets: ['latin'],
  weight: ['400', '600', '800'], 
  variable: '--font-platypi',
});

export const metadata: Metadata = {
  title: "Pastel Pomdoro App",
  description: "Generated by cynthia next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" className="h-screen">
  <body className={`${platypi.className} antialiased h-screen overflow-hidden`}>
    <div className="h-screen grid grid-cols-1 md:grid-cols-[300px_1fr] bg-background text-foreground">

      {/* Sidebar (fixed height) */}
      <Sidebar />

      {/* 🌿 Main Content (scrollable) */}
      <main className="h-full overflow-y-auto sm:p-2 max-w-4xl mx-auto w-full min-h-screen bg-background text-foreground p-2 px-6 flex items-center justify-start flex-col">
        <Header />
        {children}
      </main>

    </div>
  </body>
</html>

  );
  //  (
  //   <html lang="en">
  //     <body
  //       className={`${platypi.className} antialiased`}
  //     >
  //         <div className="min-h-screen bg-background text-foreground p-2 px-6 flex items-center justify-start flex-col">
  //           <Header />
  //         {children}
  //         </div>
        
  //     </body>
  //   </html>
  // );
}
